# Generated by Django 5.0 on 2024-02-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0002_holiday_approved_holiday_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
