# Generated by Django 5.0 on 2024-03-12 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('privilage', models.CharField(max_length=150)),
                ('group_id', models.CharField(max_length=150)),
                ('user_id', models.CharField(max_length=150)),
                ('card', models.CharField(max_length=150)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
            ],
        ),
    ]
