# Generated by Django 5.0 on 2024-03-12 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_deviceuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceuser',
            old_name='privilage',
            new_name='privilege',
        ),
    ]
