# Generated by Django 5.0 on 2024-03-12 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_rename_privilage_deviceuser_privilege'),
        ('employee', '0007_alter_employee_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceuser',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='deviceuser',
            name='uid',
            field=models.IntegerField(null=True),
        ),
    ]
