# Generated by Django 5.0 on 2025-12-19 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_deviceuser_employee_alter_deviceuser_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceuser',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_users', to='device.device'),
        ),
    ]
