# Generated by Django 5.0 on 2024-04-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_shift_current_pattern_shift_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='slug',
        ),
    ]
