# Generated by Django 5.0 on 2024-04-30 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_deviceuser_employee_alter_deviceuser_uid'),
        ('shift', '0003_remove_pattern_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='device.device'),
        ),
    ]
