version: '3.8'

networks:

  qualabels-domain:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.19.0/24

services:

  redis:
    image: redis
    ports:
      - "4371:4370"
    # networks:
    #   - qualabels-domain

  web:
    build: .
    command: [ "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini" ]
    restart: always
    volumes:
      - .:/code
    environment:
      DJANGO_SETTINGS_MODULE: qual.settings
      BROKER_URL: redis://redis:6379/0
      BROKER_BACKEND: redis://redis:6379/0
    depends_on:
      # - celery
      - redis
      - nginx
    # network_mode: "host"
    # networks:
    #   - qualabels-domain

  nginx:
    image: nginx:1.24.0
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    # networks:
    #   - qualabels-domain
    depends_on:
      - redis
    ports:
      - "80:80"
      - "443:443"
      - "4370:4370"
      # - "6380:6379"

  celery:
    build:
      context: .
    restart: always
    working_dir: /code/qual/
    volumes:
      - .:/code
    # command: celery multi start w1 -A qual -B -l debug
    command: celery -A qual worker -E -l debug
    environment:
      DJANGO_SETTINGS_MODULE: qual.settings
      BROKER_URL: redis://redis:6379/0
      RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - web
      - redis
    #   - nginx
    # networks:
    #   - qualabels-domain
    # ports:
    #   - '4372:4370'
    # network_mode: "host"
volumes:
  .:

    # celery -A myshop  flower --broker=amqp://guest:guest@localhost:5672/ --broker_api=http://guest:guest@localhost:15672/api/
