"""
Django settings for qual project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

# from __future__ import absolute_import

import os
from pathlib import Path

# from .celery import app as celery_app
ALLOWED_HOSTS = ["*"]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
LOGIN_REDIRECT_URL = "/"

# print(BASE_DIR)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!

# LOGIN_REDIRECT_URL = "attendance"
# LOGIN_URL = "login"
# LOGOUT_URL = "logout"
# DEBUG = True
# ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    # "django_admin_tailwind",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "session_security",
    "approval",
    "attendance",
    "account",
    "device",
    "employee",
    "shift",
    "leave",
    "holiday",
    "overtime",
    "compressor",
    "django_filters",
    # "celery",
    "django_flatpickr",
    "django_select2",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "session_security.middleware.SessionSecurityMiddleware",
]

ROOT_URLCONF = "qual.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "qual/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "qual.wsgi.application"
ASGI_APPLICATION = "qual.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/


# env\qual\Lib\site-packages\django\contrib\admin\static\admin\

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "qual/static/"
DEVICE_CONN_TIMEOUT = "5"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "qual/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

COMPRESS_ROOT = BASE_DIR / "qual/static/"
COMPRESS_ENABLED = True
STATICFILES_FINDERS = (
    "compressor.finders.CompressorFinder",
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)

SESSION_SECURITY_WARN_AFTER = 59 * 60
SESSION_SECURITY_EXPIRE_AFTER = 60 * 60
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


BROKER_URL = "redis://redis:6379"
RESULT_BACKEND = "redis://redis:6379"


# SELECT2_JS = ["../static/django_select2/django_select2.js"]
# SELECT2_CSS = ["../static/django_select2/django_select2.css"]
# REDIS_HOST = "redis"
# REDIS_URL = "redis://redis:6379/0"
# REDIS_PORT = 6379


# npx tailwindcss -i ./qual/qual/static/src/input.css -o ./qual/qual/static/src/output.css --watch
# c:\Users\biruk\Documents\projects\educa\env\educa\Scripts\python.exe -m pip install -U djlint


# Get-ChildItem -Recurse -Filter "__pycache__" | Remove-Item -Recurse -Force
# Get-ChildItem -Recurse -Filter "*.pyc" | Remove-Item -Force
