# Generated by Django 5.0 on 2024-02-26 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0004_alter_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('day_span', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time_expected', models.TimeField()),
                ('end_time_expected', models.TimeField()),
                ('start_time_actual', models.TimeField()),
                ('end_time_actual', models.TimeField()),
                ('worked_hours', models.DurationField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('total_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('overtime_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overtime.overtimetype')),
            ],
        ),
    ]
