# Generated by Django 5.0 on 2024-02-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimetype',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
