# Generated by Django 5.0 on 2024-03-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0003_alter_overtime_end_time_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='total_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overtimetype',
            name='rate',
            field=models.FloatField(),
        ),
    ]
