# Generated by Django 5.0 on 2024-03-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0004_alter_overtime_total_rate_alter_overtimetype_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
