# Generated by Django 5.0 on 2024-03-18 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0005_overtime_total_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overtime_approval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overtime',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
