# Generated by Django 5.0 on 2024-03-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0006_overtime_approved_by_overtime_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='total_rate',
        ),
    ]
