# Generated by Django 5.0 on 2024-03-21 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_delete_salary'),
        ('overtime', '0007_remove_overtime_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtime',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='overtime_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to='overtime.overtimetype'),
        ),
    ]
