# Generated by Django 5.0 on 2024-03-26 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_employee_options'),
        ('overtime', '0008_alter_overtime_employee_alter_overtime_overtime_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(unique=True)),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='overtime_type',
        ),
        migrations.RemoveField(
            model_name='overtimetype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='overtimetype',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='overtimetype',
            name='slug',
        ),
        migrations.AddField(
            model_name='overtimetype',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overtimetype',
            name='pay_item_code',
            field=models.CharField(blank=True, choices=[('OTE', 'OTE'), ('OTN', 'OTN'), ('OTH', 'OTH'), ('OTW', 'OTW')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='overtimetype',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overtimetype',
            name='days',
            field=models.ManyToManyField(related_name='overtime_types', to='overtime.days'),
        ),
        migrations.CreateModel(
            name='Ot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('units_worked', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ots', to='employee.employee')),
                ('overtime_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overtime.overtimetype')),
            ],
        ),
    ]
