# Generated by Django 5.0 on 2024-03-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0009_days_remove_overtime_overtime_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Days',
            new_name='Day',
        ),
    ]
