# Generated by Django 5.0 on 2024-03-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0011_ot_overtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
