# Generated by Django 5.0 on 2024-03-26 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0012_overtime_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot',
            name='overtime_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='overtime.overtimetype'),
        ),
    ]
