# Generated by Django 5.0 on 2024-04-08 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0013_alter_ot_overtime_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overtime',
            old_name='end_time_expected',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='overtime',
            old_name='start_time_expected',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='end_time_actual',
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='start_time_actual',
        ),
        migrations.AlterField(
            model_name='ot',
            name='overtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ots', to='overtime.overtime'),
        ),
        migrations.AlterField(
            model_name='ot',
            name='overtime_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ots', to='overtime.overtimetype'),
        ),
    ]
