# Generated by Django 5.0 on 2024-04-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0014_rename_end_time_expected_overtime_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
