# Generated by Django 5.0 on 2024-04-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0015_ot_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimetype',
            name='days',
            field=models.ManyToManyField(blank=True, related_name='overtime_types', to='overtime.day'),
        ),
    ]
