# Generated by Django 5.0 on 2024-04-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0016_alter_overtimetype_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ot',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='ot',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
