# Generated by Django 5.0 on 2024-05-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0017_rename_date_ot_start_date_ot_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime',
            name='worked_hours',
        ),
    ]
