# Generated by Django 5.0 on 2024-05-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0018_remove_overtime_worked_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='worked_hours',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
