# Generated by Django 5.0 on 2024-05-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0019_overtime_worked_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot',
            name='have_attendance',
            field=models.BooleanField(default=True),
        ),
    ]
