# Generated by Django 5.0 on 2024-06-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0020_ot_have_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot',
            name='have_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
