# Generated by Django 5.0 on 2024-02-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('employee', '0005_department_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manages',
            field=models.ManyToManyField(blank=True, related_name='managers', to='employee.department'),
        ),
    ]
