# Generated by Django 5.0 on 2024-02-28 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_manages'),
        ('employee', '0005_department_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
