# Generated by Django 5.0 on 2024-04-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_options'),
        ('device', '0004_deviceuser_employee_alter_deviceuser_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='device',
            field=models.ManyToManyField(blank=True, to='device.device'),
        ),
    ]
