# Generated by Django 5.0 on 2024-04-30 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_device'),
        ('device', '0004_deviceuser_employee_alter_deviceuser_uid'),
        ('employee', '0016_employee_device_alter_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='device',
        ),
        migrations.AlterField(
            model_name='profile',
            name='manages',
            field=models.ManyToManyField(blank=True, null=True, related_name='managers', to='employee.department'),
        ),
        migrations.AddField(
            model_name='profile',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device'),
        ),
    ]
