# Generated by Django 5.0 on 2024-04-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_profile_device_alter_profile_manages_and_more'),
        ('employee', '0016_employee_device_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='manages',
            field=models.ManyToManyField(blank=True, related_name='managers', to='employee.department'),
        ),
    ]
