# Generated by Django 5.0 on 2024-01-30 12:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('last_updated', models.DateField(default=datetime.datetime(2024, 1, 1, 0, 0))),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='shift.pattern')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='shift.shift')),
            ],
        ),
    ]
