# Generated by Django 5.0 on 2024-02-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
