# Generated by Django 5.0 on 2024-03-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_department_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
