# Generated by Django 5.0 on 2024-03-12 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_employee_id'),
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='shift.shift'),
        ),
    ]
