# Generated by Django 5.0 on 2024-03-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pattern',
        ),
    ]
