# Generated by Django 5.0 on 2024-03-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_remove_employee_salary_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='annual_leave_balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='annual_leave_difference',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='annual_leave_remaining',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='annual_leave_taken',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
