# Generated by Django 5.0 on 2024-03-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_employee_termination_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
