# Generated by Django 5.0 on 2024-03-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_delete_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['name']},
        ),
    ]
