# Generated by Django 5.0 on 2024-04-30 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_deviceuser_employee_alter_deviceuser_uid'),
        ('employee', '0015_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='device.device'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employee.department'),
        ),
    ]
