# Generated by Django 5.0 on 2024-07-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_employee_device_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='calculate_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='total_annual_leave_balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
