# Generated by Django 5.0 on 2024-07-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_employee_calculate_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='total_annual_leave_balance',
            new_name='total_annual_leave_taken',
        ),
    ]
