# Generated by Django 5.0 on 2024-07-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_rename_total_annual_leave_balance_employee_total_annual_leave_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='total_annual_leave_taken',
        ),
    ]
