# Generated by Django 5.0 on 2024-07-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_remove_employee_total_annual_leave_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='old_rule_balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
