# Generated by Django 5.0 on 2025-03-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_employee_old_rule_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
