# Generated by Django 5.0 on 2025-12-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_alter_employee_employee_id_alter_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='calculate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='termination_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
