# Generated by Django 5.0 on 2024-02-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='ending_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='starting_date',
            new_name='start_date',
        ),
    ]
