# Generated by Django 5.0 on 2024-02-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_rename_maximum_date_leavetype_maximum_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='leave_evidence/'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
