# Generated by Django 5.0 on 2024-02-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_alter_leave_evidence_alter_leave_reason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'permissions': [('can_approve_leave', 'Can Approve Leave')]},
        ),
        migrations.AddField(
            model_name='leave',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
