# Generated by Django 5.0 on 2024-02-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_alter_leave_options_leave_active_leave_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
