# Generated by Django 5.0 on 2024-03-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0008_leave_approved_by_leave_rejected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={},
        ),
    ]
