# Generated by Django 5.0 on 2024-04-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_alter_leave_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='evidence',
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(),
        ),
    ]
