# Generated by Django 5.0 on 2024-05-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0010_remove_leave_evidence_alter_leave_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='annual',
            field=models.BooleanField(default=False),
        ),
    ]
