# Generated by Django 5.0 on 2024-05-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0011_leavetype_annual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='is_half_day',
            new_name='half_day',
        ),
    ]
