# Generated by Django 5.0 on 2024-07-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0013_leave_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='total_days',
            field=models.IntegerField(default=False),
        ),
    ]
