# Generated by Django 5.0 on 2024-07-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0014_leave_total_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='half_day',
        ),
        migrations.AlterField(
            model_name='leave',
            name='total_days',
            field=models.FloatField(default=False),
        ),
    ]
