# Generated by Django 5.0 on 2024-07-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0015_remove_leave_half_day_alter_leave_total_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='total_days',
        ),
        migrations.AddField(
            model_name='leave',
            name='half_day',
            field=models.BooleanField(default=False),
        ),
    ]
