# Generated by Django 5.0 on 2024-07-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0017_leave_total_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='exclude_rest_days',
            field=models.BooleanField(default=False),
        ),
    ]
