# Generated by Django 5.0 on 2024-07-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0018_leavetype_exclude_rest_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='saturday_half',
            field=models.BooleanField(default=False),
        ),
    ]
