# Generated by Django 5.0 on 2025-03-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0019_leave_saturday_half'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-start_date']},
        ),
    ]
