# Generated by Django 5.0 on 2025-03-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0020_alter_leave_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
