# Generated by Django 5.0 on 2025-06-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0021_alter_leavetype_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavetype",
            name="half_day_leave",
            field=models.BooleanField(default=False),
        ),
    ]
