# Generated by Django 5.0 on 2024-01-01 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='date',
            new_name='check_in_date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='current_shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='attendance.shift'),
        ),
        migrations.AddField(
            model_name='shift',
            name='day_span',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shift',
            name='next_shift',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='previous_shift',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
