# Generated by Django 5.0 on 2024-01-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_date_attendance_check_in_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='current_shift',
            new_name='shift',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='next_shift',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='previous_shift',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='tolerance',
        ),
    ]
