# Generated by Django 5.0 on 2024-01-23 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rename_current_shift_employee_shift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='day_span',
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('day_span', models.IntegerField(default=1)),
                ('next', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_pattern', to='attendance.pattern')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='attendance.shift')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='pattern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='attendance.pattern'),
        ),
    ]
