# Generated by Django 5.0 on 2024-01-23 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_shift_day_span_pattern_employee_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_pattern', to='attendance.pattern'),
        ),
    ]
