# Generated by Django 5.0 on 2024-01-23 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_pattern_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('weekday', 'Weekday'), ('continous', 'Continous')], default='weekday'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='attendance.pattern'),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
