# Generated by Django 5.0 on 2024-01-23 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_shift_shift_type_alter_employee_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='current_pattern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.pattern'),
        ),
    ]
