# Generated by Django 5.0 on 2024-01-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_current_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='pattern',
            name='tolerance',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='shift',
            name='saturday_half',
            field=models.BooleanField(default=False),
        ),
    ]
