# Generated by Django 5.0 on 2024-01-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_pattern_end_time_pattern_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
