# Generated by Django 5.0 on 2024-01-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_pattern_end_time_alter_pattern_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='shift_type',
        ),
        migrations.AddField(
            model_name='shift',
            name='continous',
            field=models.BooleanField(default=False),
        ),
    ]
