# Generated by Django 5.0 on 2024-01-25 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_remove_shift_shift_type_shift_continous'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_updated',
            field=models.DateField(default=datetime.datetime(2024, 1, 1, 0, 0)),
        ),
    ]
