# Generated by Django 5.0 on 2024-01-30 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_employee_last_updated'),
        ('device', '0001_initial'),
        ('employee', '0001_initial'),
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawattendance',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_attendances', to='device.device'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='device.device'),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='shift',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='rawattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_attendances', to='employee.employee'),
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='next',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='shift',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='current_pattern',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shift.pattern'),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
        migrations.DeleteModel(
            name='Pattern',
        ),
    ]
