# Generated by Django 5.0 on 2024-02-05 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_alter_rawattendance_device_alter_attendance_device_and_more'),
        ('device', '0001_initial'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='leave',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.leavetype'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='device.device'),
        ),
    ]
