# Generated by Django 5.0 on 2024-02-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_attendance_leave_alter_attendance_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employees', models.IntegerField()),
                ('attendances', models.IntegerField()),
                ('late_check_in', models.IntegerField()),
                ('late_check_out', models.IntegerField()),
                ('early_check_in', models.IntegerField()),
                ('early_check_out', models.IntegerField()),
                ('absent', models.IntegerField()),
                ('day_off', models.IntegerField()),
                ('leave', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='leave',
            new_name='leave_type',
        ),
        migrations.AddField(
            model_name='attendance',
            name='absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_type',
            field=models.CharField(choices=[('late', 'Late'), ('early', 'Early'), ('on_time', 'On Time')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_type',
            field=models.CharField(choices=[('late', 'Late'), ('early', 'Early'), ('on_time', 'On Time')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='day_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='holiday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='on_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.TimeField(null=True),
        ),
    ]
