# Generated by Django 5.0 on 2024-02-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_dailyrecord_rename_leave_attendance_leave_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='leave_type',
            field=models.CharField(null=True),
        ),
    ]
