# Generated by Django 5.0 on 2024-02-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_alter_attendance_leave_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='absent',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='day_off',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='holiday',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='on_leave',
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('checked_in', 'Checked In'), ('absent', 'Absent'), ('day_off', 'Day Off'), ('on_leave', 'On Leave'), ('holiday', 'Holiday')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='worked_hours',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in_type',
            field=models.CharField(choices=[('late', 'Late'), ('early', 'Early'), ('on_time', 'On Time'), ('no_data', 'No Data')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out_type',
            field=models.CharField(choices=[('late', 'Late'), ('early', 'Early'), ('on_time', 'On Time'), ('no_data', 'No Data')], max_length=10, null=True),
        ),
    ]
