# Generated by Django 5.0 on 2024-02-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_alter_attendance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in_type',
            field=models.CharField(choices=[('Late', 'Late'), ('Early', 'Early'), ('On Time', 'On Time'), ('No Data', 'No Data')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out_type',
            field=models.CharField(choices=[('Late', 'Late'), ('Early', 'Early'), ('On Time', 'On Time'), ('No Data', 'No Data')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Checked In', 'Checked In'), ('Absent', 'Absent'), ('Day Off', 'Day Off'), ('On Leave', 'On Leave'), ('Holiday', 'Holiday')], max_length=10, null=True),
        ),
    ]
