# Generated by Django 5.0 on 2024-02-24 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_alter_attendance_check_in_type_and_more'),
        ('leave', '0006_alter_leave_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_type', to='leave.leavetype'),
        ),
    ]
