# Generated by Django 5.0 on 2024-03-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_alter_attendance_check_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawattendance',
            name='punch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rawattendance',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rawattendance',
            name='uid',
            field=models.CharField(max_length=50),
        ),
    ]
