# Generated by Django 5.0 on 2024-04-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_attendance_approved_by_attendance_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
