# Generated by Django 5.0 on 2024-04-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_attendance_recalculated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='recalculated',
            new_name='recompiled',
        ),
    ]
