# Generated by Django 5.0 on 2024-04-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_rename_recalculated_attendance_recompiled'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='holiday',
            field=models.IntegerField(null=True),
        ),
    ]
