# Generated by Django 5.0 on 2024-04-30 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_dailyrecord_holiday'),
        ('device', '0004_deviceuser_employee_alter_deviceuser_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device'),
        ),
    ]
