# Generated by Django 5.0 on 2025-01-04 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_attendance_compile_date_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='compile_date',
            field=models.DateField(default=datetime.date(2025, 1, 4)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Checked', 'Checked'), ('No Data', 'No Data'), ('Absent', 'Absent'), ('Day Off', 'Day Off'), ('On Leave', 'On Leave'), ('On Field', 'On Field'), ('Holiday', 'Holiday')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='OnField',
        ),
    ]
