# Generated by Django 5.0 on 2025-01-04 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0033_alter_attendance_compile_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='compile_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 4, 13, 31, 20, 908521)),
        ),
    ]
