# Generated by Django 5.0 on 2025-01-04 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0034_alter_attendance_compile_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='compile_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 4, 13, 32, 1, 278241)),
        ),
    ]
