# Generated by Django 5.0 on 2025-03-11 12:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0035_alter_attendance_compile_date'),
        ('leave', '0020_alter_leave_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='compile_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_type', to='leave.leavetype'),
        ),
    ]
