# Generated by Django 5.0 on 2025-12-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0036_alter_attendance_compile_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawattendance',
            options={'ordering': ['-date', '-time']},
        ),
    ]
